"""
Valida streaming incremental do chat e persistencia do fechamento da conversa.
"""
from __future__ import annotations

import json as jsonlib
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from soc_copilot import config as cfg
from soc_copilot.modules import chat_service, persistence

PASS = "PASS"
FAIL = "FAIL"
resultados: list[tuple[str, str, str]] = []


def check(nome: str, condicao: bool, detalhe: str = "") -> None:
    status = PASS if condicao else FAIL
    resultados.append((status, nome, detalhe))


class FakeStreamResponse:
    def __init__(self, lines: list[str]) -> None:
        self._lines = lines

    def raise_for_status(self) -> None:
        return None

    def iter_lines(self, decode_unicode: bool = True):
        for line in self._lines:
            yield line if decode_unicode else line.encode("utf-8")

    def close(self) -> None:
        return None


tmpdir = tempfile.TemporaryDirectory()
db_path = Path(tmpdir.name) / "test_chat_stream.db"
persistence.DB_PATH = db_path
persistence.init_db()

original_enabled = cfg.LLM_ENABLED
original_provider = cfg.LLM_PROVIDER
original_timeout = cfg.LLM_TIMEOUT
original_url = cfg.OLLAMA_URL
original_model = cfg.OLLAMA_MODEL
original_post = chat_service.requests.post
original_cpu_guard = os.environ.get("SOCC_CPU_GUARD_ENABLED")
original_fast_model = os.environ.get("SOCC_OLLAMA_FAST_MODEL")


try:
    consultive_skill = chat_service.select_skill("esse payload foi extraído de um alerta no QRadar")
    triage_skill = chat_service.select_skill('analise este payload {"srcip":"8.8.8.8","dstip":"10.0.0.5","action":"blocked","logid":"1"}')
    check("stream_skill_payload_reference_prefers_generalist", consultive_skill == "soc-generalist", consultive_skill)
    check("stream_skill_explicit_triage_prefers_payload", triage_skill == "payload-triage", triage_skill)
    check(
        "stream_strip_repeated_greeting_history",
        chat_service._strip_repeated_greeting("Olá! Seguindo no caso, isso parece benigno.", has_session_history=True)
        == "Seguindo no caso, isso parece benigno.",
    )
    check(
        "stream_keep_greeting_first_turn",
        chat_service._strip_repeated_greeting("Olá! Posso ajudar.", has_session_history=False) == "Olá! Posso ajudar.",
    )
except Exception as exc:
    check("stream_skill_selection_flow", False, str(exc))


try:
    cfg.LLM_ENABLED = False
    events = list(
        chat_service.stream_chat_reply_events(
            "Quais formatos de log sao suportados?",
            session_id="stream-fallback",
            cliente="Cliente Teste",
        )
    )
    final_event = next((item for item in events if item.get("event") == "final"), {})
    delta_events = [item for item in events if item.get("event") == "delta"]
    messages = persistence.list_chat_messages("stream-fallback", limit=10)

    check("stream_fallback_has_meta", events[0].get("event") == "meta")
    check("stream_fallback_has_deltas", len(delta_events) >= 1)
    check(
        "stream_fallback_final_message",
        isinstance(final_event.get("data"), dict)
        and final_event["data"].get("type") == "message"
        and (
            "Resumo do pedido" in final_event["data"].get("content", "")
            or "Pergunta registrada" in final_event["data"].get("content", "")
        ),
    )
    check("stream_fallback_persisted_exchange", len(messages) == 2)
except Exception as exc:
    check("stream_fallback_flow", False, str(exc))


try:
    cfg.LLM_ENABLED = False
    persistence.save_chat_message(
        "stream-hygiene-context",
        "user",
        '{"Operation":"HygieneTenantEvents","Workload":"SecurityComplianceCenter","Event":"Listed","ResultStatus":"Succeeded","EventValue":"CTE.SADA@SADA.COM.BR","Audit":"Generated by OBP2SenderRepService - Object Store: 1535;SpamRule=46603;","Reason":"RecipientRateLimitExceeded;RecipientCountLast24Hours=10002;RcptRateLimit=10000;"}',
        skill="soc-generalist",
    )
    events = list(
        chat_service.stream_chat_reply_events(
            "isso é o que eu estou te perguntando. com a sua base de dados, o que você consegue concluir?",
            session_id="stream-hygiene-context",
            cliente="Cliente Teste",
            response_mode="fast",
        )
    )
    final_event = next((item for item in events if item.get("event") == "final"), {})
    final_data = final_event.get("data") if isinstance(final_event.get("data"), dict) else {}
    final_text = str(final_data.get("content") or "")
    final_meta = final_data.get("metadata") if isinstance(final_data, dict) else {}
    check(
        "stream_hygiene_deterministic_reply",
        "Leitura determinística do evento:" in final_text
        and "OBP2SenderRepService" in final_text
        and "incidente confirmado" in final_text,
        final_text,
    )
    check("stream_hygiene_deterministic_done_reason", isinstance(final_meta, dict) and final_meta.get("done_reason") == "deterministic", str(final_meta))
except Exception as exc:
    check("stream_hygiene_context_flow", False, str(exc))


try:
    cfg.LLM_ENABLED = True
    cfg.LLM_PROVIDER = "ollama"
    cfg.OLLAMA_URL = "http://ollama.test"
    cfg.OLLAMA_MODEL = "qwen3.5:9b"
    cfg.LLM_TIMEOUT = 5
    os.environ["SOCC_CPU_GUARD_ENABLED"] = "false"
    os.environ["SOCC_OLLAMA_FAST_MODEL"] = "llama3.2:3b"

    def fake_post(url: str, json: dict, timeout: float, stream: bool = False):
        check("stream_ollama_uses_stream_flag", stream is True, str(stream))
        check("stream_ollama_hits_chat_api", url.endswith("/api/chat"), url)
        check("stream_ollama_fast_model", str(json.get("model") or "") == "llama3.2:3b", str(json.get("model")))
        check("stream_ollama_fast_num_predict_absent", "num_predict" not in (json.get("options") or {}), str(json.get("options")))
        check("stream_ollama_fast_num_ctx", int((json.get("options") or {}).get("num_ctx") or 0) == 3072, str(json.get("options")))
        check("stream_ollama_keep_alive", str(json.get("keep_alive") or "") == "15m", str(json.get("keep_alive")))
        return FakeStreamResponse(
            [
                json_module
                for json_module in (
                    jsonlib.dumps({"message": {"content": "Resposta "}, "done": False}),
                    jsonlib.dumps({"message": {"content": "incremental"}, "done": False}),
                    jsonlib.dumps({"message": {"content": "."}, "done": True}),
                )
            ]
        )

    chat_service.requests.post = fake_post
    events = list(
        chat_service.stream_chat_reply_events(
            "Explique este alerta em uma frase.",
            session_id="stream-ollama",
            cliente="Cliente Teste",
            response_mode="fast",
        )
    )
    delta_text = "".join(item.get("delta", "") for item in events if item.get("event") == "delta")
    final_event = next((item for item in events if item.get("event") == "final"), {})
    final_data = final_event.get("data") if isinstance(final_event.get("data"), dict) else {}
    messages = persistence.list_chat_messages("stream-ollama", limit=10)

    check("stream_ollama_has_multiple_deltas", delta_text == "Resposta incremental.")
    check(
        "stream_ollama_final_matches_deltas",
        isinstance(final_data, dict) and final_data.get("content") == delta_text,
    )
    check(
        "stream_ollama_persisted_assistant",
        len(messages) == 2 and any(
            item.get("role") == "assistant" and item.get("content") == "Resposta incremental."
            for item in messages
        ),
    )
    persisted_assistant = next((item for item in messages if item.get("role") == "assistant"), {})
    persisted_user = next((item for item in messages if item.get("role") == "user"), {})
    check(
        "stream_ollama_final_response_mode",
        isinstance(final_data, dict) and (final_data.get("metadata") or {}).get("response_mode") == "fast",
    )
    check(
        "stream_ollama_final_not_truncated",
        isinstance(final_data, dict) and (final_data.get("metadata") or {}).get("truncated") is False,
    )
    check(
        "stream_ollama_persisted_assistant_metadata_content",
        isinstance(persisted_assistant.get("metadata"), dict)
        and persisted_assistant["metadata"].get("content") == "Resposta incremental.",
        str(persisted_assistant),
    )
    check(
        "stream_ollama_persisted_assistant_metadata_mode",
        isinstance((persisted_assistant.get("metadata") or {}).get("metadata"), dict)
        and (persisted_assistant.get("metadata") or {}).get("metadata", {}).get("response_mode") == "fast",
        str(persisted_assistant),
    )
    check(
        "stream_ollama_persisted_user_metadata_content",
        isinstance(persisted_user.get("metadata"), dict)
        and persisted_user["metadata"].get("content") == "Explique este alerta em uma frase.",
        str(persisted_user),
    )
except Exception as exc:
    check("stream_ollama_flow", False, str(exc))


try:
    cfg.LLM_ENABLED = True
    cfg.LLM_PROVIDER = "ollama"
    cfg.OLLAMA_URL = "http://ollama.test"
    cfg.OLLAMA_MODEL = "qwen3.5:9b"
    cfg.LLM_TIMEOUT = 5
    os.environ["SOCC_CPU_GUARD_ENABLED"] = "false"

    request_counter = {"count": 0}

    def fake_post_truncated(url: str, json: dict, timeout: float, stream: bool = False):
        request_counter["count"] += 1
        if request_counter["count"] == 1:
            check(
                "stream_ollama_truncated_balanced_num_predict_absent",
                "num_predict" not in (json.get("options") or {}),
                str(json.get("options")),
            )
            return FakeStreamResponse(
                [
                    jsonlib.dumps({"message": {"content": "Primeira parte. "}, "done": False}),
                    jsonlib.dumps({"message": {"content": "Segunda parte"}, "done": False}),
                    jsonlib.dumps({"done": True, "done_reason": "length"}),
                ]
            )
        check(
            "stream_ollama_truncated_continuation_prompt",
            "Continue exatamente de onde voce parou" in str((json.get("messages") or [])[-1].get("content") or ""),
            str((json.get("messages") or [])[-1]),
        )
        return FakeStreamResponse(
            [
                jsonlib.dumps({"message": {"content": " concluída."}, "done": False}),
                jsonlib.dumps({"done": True, "done_reason": "stop"}),
            ]
        )

    chat_service.requests.post = fake_post_truncated
    events = list(
        chat_service.stream_chat_reply_events(
            "Explique o alerta com começo, meio e fim.",
            session_id="stream-ollama-truncated",
            cliente="Cliente Teste",
            response_mode="balanced",
        )
    )
    final_event = next((item for item in events if item.get("event") == "final"), {})
    final_data = final_event.get("data") if isinstance(final_event.get("data"), dict) else {}
    final_metadata = final_data.get("metadata") if isinstance(final_data, dict) else {}

    check("stream_ollama_truncated_second_call", request_counter["count"] == 2, str(request_counter))
    check(
        "stream_ollama_truncated_content_completed",
        isinstance(final_data, dict) and final_data.get("content") == "Primeira parte. Segunda parte concluída.",
        str(final_data),
    )
    check(
        "stream_ollama_truncated_metadata_continuation",
        isinstance(final_metadata, dict)
        and final_metadata.get("continuation_used") is True
        and final_metadata.get("truncated") is False
        and final_metadata.get("done_reason") == "length"
        and final_metadata.get("continuation_done_reason") == "stop",
        str(final_metadata),
    )
except Exception as exc:
    check("stream_ollama_truncated_flow", False, str(exc))
finally:
    cfg.LLM_ENABLED = original_enabled
    cfg.LLM_PROVIDER = original_provider
    cfg.LLM_TIMEOUT = original_timeout
    cfg.OLLAMA_URL = original_url
    cfg.OLLAMA_MODEL = original_model
    chat_service.requests.post = original_post
    if original_cpu_guard is None:
        os.environ.pop("SOCC_CPU_GUARD_ENABLED", None)
    else:
        os.environ["SOCC_CPU_GUARD_ENABLED"] = original_cpu_guard
    if original_fast_model is None:
        os.environ.pop("SOCC_OLLAMA_FAST_MODEL", None)
    else:
        os.environ["SOCC_OLLAMA_FAST_MODEL"] = original_fast_model


print(f"\n{'='*60}")
print(f"SOC Copilot — Chat Streaming  ({len(resultados)} checks)")
print("=" * 60)
falhas = [(n, d) for s, n, d in resultados if s == FAIL]
aprovados = len(resultados) - len(falhas)
print(f"  Aprovados : {aprovados}/{len(resultados)}")
print(f"  Falhas    : {len(falhas)}/{len(resultados)}")
print()
for nome, detalhe in falhas:
    extra = f" — {detalhe}" if detalhe else ""
    print(f"  FALHA: {nome}{extra}")
if not falhas:
    print("  Todos os checks passaram.")
print()

tmpdir.cleanup()
sys.exit(1 if falhas else 0)
